import { Pickup } from "./models"

export const pickup: Pickup = {
	id: "2023",
	name: "2023年",
	bannerUrl: "/pu/2023_banner.png",
	puImageUrl: "/pu/2023.png",
	characters: [
		{
			id: "banimiko",
			luck: "星5吉",
			name: "バニ神子ドン美",
			image: "/characters/banimiko.png",
			thumbnail: "/characters/banimiko_small.png",
			stars: 5,
		},
		{
			id: "dirudonmi",
			luck: "星5吉",
			name: "ディルドン美",
			image: "/characters/dirudo.png",
			thumbnail: "/characters/dirudo_small.png",
			stars: 5,
		},
		{
			id: "daikici",
			luck: "大吉",
			name: "ドン美(大吉)",
			image: "/characters/large.png",
			thumbnail: "/characters/large_small.png",
			stars: 4,
		},
		{
			id: "chukichi",
			luck: "中吉",
			name: "ドン美(中吉)",
			image: "/characters/middle.png",
			thumbnail: "/characters/middle_small.png",
			stars: 3,
		},
		{
			id: "chukichi",
			luck: "吉",
			name: "ドン美(吉)",
			image: "/characters/normal.png",
			thumbnail: "/characters/normal_small.png",
			stars: 3,
		},
		{
			id: "small",
			luck: "小吉",
			name: "ドン美(小吉)",
			image: "/characters/small.png",
			thumbnail: "/characters/small_small.png",
			stars: 2,
		},
		{
			id: "bottom",
			luck: "末吉",
			name: "ドン美(末吉)",
			image: "/characters/bottom.png",
			thumbnail: "/characters/bottom_small.png",
			stars: 2,
		},
		{
			id: "bad",
			luck: "凶",
			name: "ドン美(凶)",
			image: "/characters/bad.png",
			thumbnail: "/characters/bad_small.png",
			stars: 1,
		},
	],
}
